CREATE OR REPLACE PROCEDURE DISTINCTION IS

	CURSOR RESULT_CURSOR IS
	SELECT SNAME,RNO,PERCENT FROM STUDENT
	WHERE PERCENT>=70;
	
	F_SNAME STUDENT.SNAME%TYPE;
	F_RNO STUDENT.RNO%TYPE;
	F_PERCENT STUDENT.PERCENT%TYPE;
	TOTAL NUMBER(2);

BEGIN
	TOTAL:=0;
	OPEN RESULT_CURSOR;
	LOOP
	FETCH RESULT_CURSOR INTO F_SNAME,F_RNO,F_PERCENT;
	EXIT WHEN RESULT_CURSOR%NOTFOUND;
	DBMS_OUTPUT.PUT_LINE('************************************************************************');
	DBMS_OUTPUT.PUT_LINE('STUDENT NAME='||F_SNAME);
	DBMS_OUTPUT.PUT_LINE('STUDENT ROLLNO='||F_RNO);
	DBMS_OUTPUT.PUT_LINE('PERCENTAGE SCORED='||F_PERCENT);
	TOTAL:=12;
	END LOOP;
	IF(TOTAL<>12) THEN
	DBMS_OUTPUT.PUT_LINE('SORRY NO RECORD SELECTED');
	END IF;
	
EXCEPTION
	WHEN OTHERS THEN
	DBMS_OUTPUT.PUT_LINE('AN EXCEPTION IS RAISED IN PROCEDURE DISTINCTION');
END DISTINCTION;


